"""Romaji generated by code from kana/Japanese, never by the LLM.

SPEC FR-9 / 8.3: the LLM's kana is verified first (verify_lesson), then this
module transliterates it. Hepburn output via pykakasi, offline.
"""

from __future__ import annotations

import threading

_converter = None
_lock = threading.Lock()


def _get_converter():
    global _converter
    if _converter is None:
        with _lock:
            if _converter is None:
                import pykakasi

                _converter = pykakasi.kakasi()
    return _converter


def to_romaji(text: str) -> str:
    """Transliterate kana or kanji-bearing Japanese to Hepburn romaji."""
    segments = _get_converter().convert(text)
    return " ".join(seg["hepburn"] for seg in segments).strip()


def kana_to_romaji(kana: str) -> str:
    """Transliterate pure kana (e.g. a verified word reading)."""
    return to_romaji(kana)
