from typing import Literal

from pydantic import BaseModel, Field

class KanjiFacts(BaseModel):
    """Verified kanji facts from KANJIDIC2, never LLM-authored. See docs/SPEC.md 7.3."""

    kanji: str = Field(description="The kanji character itself (e.g., 水)")
    onyomi: list[str] = Field(description="On'yomi readings in katakana (e.g., ['スイ'])")
    kunyomi: list[str] = Field(description="Kunyomi readings in hiragana (e.g., ['みず'])")
    meanings: list[str] = Field(description="English meanings (e.g., ['water'])")
    stroke_count: int | None = Field(default=None, description="Stroke count from KANJIDIC2")
    grade: int | None = Field(default=None, description="School grade from KANJIDIC2, None if ungraded")

    def to_polished_string(self) -> str:
        return (
            f"On'yomi: {', '.join(self.onyomi) or '—'}\n"
            f"Kunyomi: {', '.join(self.kunyomi) or '—'}\n"
            f"Meanings: {', '.join(self.meanings) or '—'}\n"
            f"Strokes: {self.stroke_count if self.stroke_count is not None else '—'}"
            f" | Grade: {self.grade if self.grade is not None else '—'}"
        )

class KanjiExample(BaseModel):
    word: str = Field(description="The example word containing the kanji (e.g., 火山)")
    kana: str = Field(description="The reading in hiragana or katakana (e.g., かざん)")
    romaji: str = Field(description="The romaji reading (e.g., kazan)")
    meaning: str = Field(description="The English meaning of the word (e.g., volcano)")

    def __str__(self):
        return f"{self.word} [{self.kana}] ({self.romaji}) - {self.meaning}"

class VerifiedWord(BaseModel):
    """An example word confirmed in JMdict. Romaji is filled by code, never the LLM."""

    word: str = Field(description="Example word containing the target kanji (e.g., 水泳)")
    kana: str = Field(description="Verified kana reading (e.g., すいえい)")
    meaning: str = Field(description="English meaning (e.g., swimming)")
    romaji: str = Field(default="", description="Romaji generated by code from kana. Leave blank.")

    def __str__(self):
        romaji = f" ({self.romaji})" if self.romaji else ""
        return f"{self.word} [{self.kana}]{romaji} - {self.meaning}"

class DialogueLine(BaseModel):
    speaker: str = Field(description="The name or role of the speaker (e.g., Akira, Shopkeeper).")
    japanese: str = Field(description="What the speaker says in Japanese. MUST include at least one vocabulary word using the target kanji.")
    english: str = Field(description="The English translation of the Japanese line.")
    romaji: str = Field(default="", description="Romaji generated by code from the Japanese line. Leave blank.")
    flagged: bool = Field(default=False, description="Set by the dialogue judge pass, never by the lesson author.")

class ReadingUsage(BaseModel):
    onyomi_rule: str = Field(
        description="Explanation of when to use the On'yomi reading for this kanji. Often used in multi-kanji compound words (jukugo)."
    )
    kunyomi_rule: str = Field(
        description="Explanation of when to use the Kun'yomi reading for this kanji. Often used for standalone words or with trailing hiragana (okurigana)."
    )

class KanjiLesson(BaseModel):
    usage_guidelines: ReadingUsage = Field(description="Rules of thumb for when to use the On'yomi vs Kun'yomi readings for this specific kanji.")
    words: list[VerifiedWord] = Field(description="Example words. Every word MUST contain the target kanji. Leave each romaji blank.")
    mnemonic: str = Field(description="A short memory aid for the kanji (story, visual, radicals). Labelled as a memory aid, never presented as historical fact.")
    dialogue: list[DialogueLine] = Field(description="A short, simple 2-4 line conversation demonstrating the target kanji being used naturally in context. Leave each romaji blank.")

    def to_polished_string(self) -> str:
        words_str = "\n".join(f"- {w}" for w in self.words) or "- (no verified words yet)"
        dialogue_str = ""
        for line in self.dialogue:
            romaji = f"\n    ({line.romaji})" if line.romaji else ""
            dialogue_str += (
                f"{line.speaker}: {line.japanese}"
                f"{romaji}\n"
                f"    {line.english}\n\n"
            )

        return (
            f"Example Words:\n{words_str}\n\n"
            f"Memory Aid:\n{self.mnemonic}\n\n"
            f"When to use which reading?\n"
            f"- On'yomi: {self.usage_guidelines.onyomi_rule}\n"
            f"- Kun'yomi: {self.usage_guidelines.kunyomi_rule}\n\n"
            f"Practice Dialogue:\n{dialogue_str}"
        )
     
class QuizQuestion(BaseModel):
    """One graded quiz question. Type coverage is enforced in code (SPEC 8.1)."""

    type: Literal["reading", "meaning", "word_reading", "word_meaning", "in_context_reading", "onkun_choice"] = Field(description="Skill type. Restricted to the allowed list when coverage requires it.")
    prompt: str = Field(description="The question text shown to the learner. Never includes the answer.")
    expected: str = Field(description="The expected answer, revealed on miss or dont_know")


class QuizAttempt(BaseModel):
    """One graded answer. The single source of truth for mastery (SPEC 8.1)."""

    question: QuizQuestion = Field(description="The question that was asked, echoed verbatim")
    user_answer: str = Field(description="The learner's raw answer text")
    outcome: Literal["correct", "miss", "dont_know"] = Field(description="Grading outcome")
    feedback: str = Field(description="Encouraging feedback that reveals the correct answer on miss")


class QuizGrade(BaseModel):
    """LLM grading verdict. The node assembles the QuizAttempt so the model
    can never rewrite the question it graded. Never stored in state."""

    outcome: Literal["correct", "miss"] = Field(description="Grading verdict")
    feedback: str = Field(description="Encouraging feedback that reveals the correct answer on miss")


class ReplyIntent(BaseModel):
    """One classified user reply. The label is constrained in code to the
    calling prompt's allowed set (see graph.helpers.PROMPT_LABELS)."""

    label: str = Field(description="The reply label, one of the prompt's allowed labels")
    reason: str = Field(default="", description="One-line reason for the label")